jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: adopt
        java-version: '13'
    - continue-on-error: true
      name: Run tests and javadoc
      run: ./gradlew check javadoc
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
