jobs:
  publishRelease:
    environment: release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      env:
        GRADLE_PUBLISH_MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
        GRADLE_PUBLISH_MAVEN_USER: ${{secrets.MAVEN_USER}}
        GRADLE_PUBLISH_REPO_URL: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2
        GRADLE_SIGNING_KEY: ${{secrets.SIGNING_KEY}}
        GRADLE_SIGNING_PASSWORD: ${{secrets.SIGNING_PASSPHRASE}}
      if: endsWith(github.event.release.tag_name, '.RELEASE')
      name: Publish Release
      run: ./gradlew --no-daemon -Pversion="${{github.event.release.tag_name}}" sign
        publish
    - continue-on-error: true
      env:
        GRADLE_PUBLISH_MAVEN_PASSWORD: ${{secrets.ARTIFACTORY_PASSWORD}}
        GRADLE_PUBLISH_MAVEN_USER: ${{secrets.ARTIFACTORY_USERNAME}}
        GRADLE_PUBLISH_REPO_URL: https://repo.spring.io/libs-milestone-local/
      if: github.event.release.prerelease && (contains(github.event.release.tag_name,
        '.M') || contains(github.event.release.tag_name, '.RC'))
      name: Publish Milestone
      run: ./gradlew --no-daemon -Pversion="${{github.event.release.tag_name}}" publish
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
