jobs:
  checkSnapshot:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: adopt
        java-version: '13'
    - continue-on-error: true
      name: Run tests and javadoc
      run: ./gradlew check javadoc
  publishSnapshot:
    env:
      BLOCKHOUND_VERSION: 1.0.10.BUILD-SNAPSHOT
    environment: snapshot
    needs: checkSnapshot
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ !endsWith(env.BLOCKHOUND_VERSION, '.BUILD-SNAPSHOT') }}
      name: check version
      run: 'echo "::error ::$BLOCKHOUND_VERSION is not following the x.y.z.BUILD-SNAPSHOT
        format"

        exit 1

        '
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      env:
        GRADLE_PUBLISH_MAVEN_PASSWORD: ${{secrets.ARTIFACTORY_PASSWORD}}
        GRADLE_PUBLISH_MAVEN_USER: ${{secrets.ARTIFACTORY_USERNAME}}
        GRADLE_PUBLISH_REPO_URL: https://repo.spring.io/libs-snapshot-local/
      name: Publish Snapshot
      run: ./gradlew --no-daemon -Pversion=$BLOCKHOUND_VERSION publish
name: Snapshot
on:
  repository_dispatch:
    types: trigger-ga___snapshot.yml
